name = 'bpsub'
main = "_worker.js"
compatibility_date = "2024-01-01"
keep_vars = true

[vars]
ADD = "https://raw.githubusercontent.com/laityts/ddns/refs/heads/main/add.txt"
SUBAPI = "sub.vlato.site"
SUBCONFIG = "https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/config/ACL4SSR_Online_Mini_MultiMode_CF.ini"
SUBNAME = "BPSUB"

# Observability 配置
[observability]
enabled = true
